### ISSUE TITLE
🐱 But... how?

### ISSUE THREAD

**Issue by CosasDePuma** [jpt/meow#1]
I really found this extremely interesenting. How do you change words when type any space?

`Edit:` Maybe [Glyphs](https://glyphsapp.com/tutorials/scripting-glyphs-part-1) are the key?

**Comment by jpt** [comment]
Hi @CosasDePuma 

Instead of changing words after every space, it actually changes words after every four characters. 

Glyphs is software for designing and building fonts. The trick in Meow is not related to Glyphs; rather it is related to a font format called OpenType and a feature in fonts called ligatures (you can read about ligatures here in [English](https://en.wikipedia.org/wiki/Orthographic_ligature) or [Spanish](https://es.wikipedia.org/wiki/Ligadura_(tipograf%C3%ADa))).

A common ligature, like `fi`, looks for any instance of the character `f` followed by the character `i`, and replaces those letters with a separate design that contains both letters.

In Meow, there is a ligature  with all the letters `meow`. And instead of the font looking for `f` followed by `i` for example, it uses OpenType features to look for any four letters in a row, and then replaces them with the `meow` letters. [This script](https://github.com/jpt/meow/blob/master/tools/make_ligs.py) generated the OpenType features. 

I hope this helps!
Jeremy
